export const ActionTypes = {
    SET_BUDGETS : "SET_BUDGETS",
    SELECTED_BUDGET: "SELECTED_BUDGET",
    REMOVE_SELECTED_BUDGET : "REMOVE_SELECTED_BUDGET",

    SET_USER : "SET_USER",
    REMOVE_USER : "REMOVE_USER"
}