export const ActionTypes = {
    SET_BUDGETS : "SET_BUDGETS",
    SELECTED_BUDGET: "SELECTED_BUDGET",
    REMOVE_SELECTED_BUDGET : "REMOVE_SELECTED_BUDGET",
    ADD_BUDGET : "ADD_BUDGET",
    UPDATE_BALANCE: "UPDATE_BALANCE",

    SET_USER : "SET_USER",
    REMOVE_USER : "REMOVE_USER"
}